#################################################################
###################### Hexo Configuration #######################
#################################################################

title: Co1In

keywords: "Hexo, NexT"

language: en

author: Colin Chen

description: hahaha

index_generator:
  per_page: 4
  order_by: -date

archive_generator:
  per_page: 8
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

timezone: UTC

url: https://www.co1in.com
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

skip_render:
  - "robots.txt"

new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 5
pagination_dir: page

theme: next

deploy:
  type: git
  repo: https://github.com/theme-next/theme-next.org.git
  branch: gh-pages
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

server:
  port: 4000

kramed:
  # For preserve original quotes in code blocks.
  smartypants: false

search:
  path: search.json
  field: all

symbols_count_time:
  symbols: false
  time: false
  total_symbols: false
  total_time: false

#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:
  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  reminder: true

  minify: true

  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  author: Colin Chen

  footer:
    since: 2014
    icon:
      name: heart
      animated: true
      color: "#808080"
    copyright: NexT
    powered:
      enable: false
      version: false
    theme:
      enable: false
      version: false

  creative_commons:
    license: by-nc-sa
    sidebar: true

  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    home: / || bullhorn

    Docs:
      default: /docs/ || book

      Advanced Settings: /advanced-settings.html || cogs
      FAQ's: /faqs.html || life-ring
      Troubleshooting: /troubleshooting.html || bug
    archives: /archives/ || archive
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  menu_settings:
    icons: true
    badges: true

  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  sidebar:
    position: left
    display: post
    padding: 18
    offset: 12
    onmobile: true

  avatar:
    # Replace the default image and set the url here.
    url: /uploads/avatar.jpg?x-oss-process=image/resize,p_20
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: false

  social:
    GitHub: https://github.com/co1in9 || github
    E-Mail: mailto:me@co1in.com || envelope
    # RSS: /atom.xml || rss

    # Gitter: https://gitter.im/theme-next || github-alt
    # Riot: https://riot.im/app/#/room/#NexT:matrix.org || bullhorn

    WeChat: /uploads/wechat.jpg || wechat

    Telegram [Chat]: https://t.me/joinchat/GUNHXA-vZkgSMuimL1VmMw || telegram
    # Telegram [News]: https://t.me/theme_next || paper-plane

  social_icons:
    enable: true
    icons_only: true
    transition: true

  toc:
    enable: true
    number: true
    wrap: true

  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 4
    wpm: 275

  post_edit:
    enable: true
    url: https://github.com/theme-next/theme-next.org/edit/source/source/

  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true

  back2top:
    enable: true
    sidebar: false
    scrollpercent: true

  # github_banner:
  #   enable: true
  #   permalink: https://github.com/theme-next/hexo-theme-next
  #   title: Fork NexT on GitHub

  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  seo: true

  index_with_subtitle: true

  exturl: true

  yandex_site_verification: 3ac9ae36ddebb425

  # ============================================================= #
  # =============== Third Party Services Settings =============== #
  # ============================================================= #

  math:
    per_page: true
    mathjax:
      enable: true

  mediumzoom: true

  lazyload: true

  # ============================================================= #
  # =================== Comments and Widgets ==================== #
  # ============================================================= #

  disqus:
    enable: true
    shortname: theme-next
    count: true
    lazyload: true

  # ============================================================= #
  # ================= Statistics and Analytics ================== #
  # ============================================================= #

  # ============================================================= #
  # ====================== Search Services ====================== #
  # ============================================================= #

  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
    preload: true

  # ============================================================= #
  # ======================== Tag Plugins ======================== #
  # ============================================================= #

  note:
    style: simple
    icons: true
    light_bg_offset: -3

  tabs:
    transition:
      tabs: true
      labels: true

  # ============================================================= #
  # ==================== External Libraries ===================== #
  # ============================================================= #

  motion:
    enable: false
